name: lp
dependencies:
- python=3.8
- pip
- r-base=3.6.1
- r-jsonlite
- r-bnlearn
- pip:
  - networkx~=2.5
  - graphviz~=0.15
  - pandas~=1.1.4
  - rpy2~=3.3.6
  - sklearn
  - matplotlib
  - numpy~=1.20.3
